name: angular_hello_world
description: >
  Hello World Example of AngularDart.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/angular_hello_world

environment:
  sdk: ">=1.25.0-dev <2.0.0"

dependencies:
  angular: "^4.0.0"

transformers:
  - angular:
      entry_points:
        - web/main.dart
  - $dart2js:
      commandLineOptions:
        - --dump-info
        - --trust-type-annotations
        - --trust-primitives
